jhipster/generator-jhipster-svelte

- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/components/auth/auth-service.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/AccountMenu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/Navbar.svelte.ejs
Closes #9 
Closes #3 
- Integrates session logout
- Removes Home navigation icon as that's redundant
- Add new Account menu with link to logout
> Integrate logout and display account menu

- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/components/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/AccountMenu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/login.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/tailwind.css.ejs
- generators/client/templates/svelte/src/main/webapp/app/utils/validator.js.ejs
- generators/client/templates/svelte/tailwind.config.js.ejs
Closes #8 
- Initial field validation framework support
- Integrate validations into Input control
- Integrate required field validations on the login page
- Remove deprecation warning on tailwind css
> Support field validations

- package-lock.json
- package.json
Support `generator-jhipster` version `6.10.3`
> Bump generator-jhipster dependency

- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/client.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/account-service.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/activate.svelte.ejs
Closes #23 
---
With this page, we should have a complete end to end working of `SignUp` --> `Activate` --> `Sign In` --> `Sign Out` :100:
> Add account activation page

- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/components/account/PasswordConfirm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/account-service.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/password-reset.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/finish.svelte.ejs
> Add page to reset user password via reset link

- generators/app/index.js
- generators/app/prompts.js
- generators/client/index.js
- generators/common/templates/src/main/resources/banner.txt.ejs
> Override app generator, i18n prompts, branding

- generators/client/templates/svelte/src/main/webapp/app/service-worker.js.ejs
> Ignore vary header in bundlers cache

- generators/app/index.js
- generators/client/index.js
- generators/client/templates/svelte/package.json.ejs
- generators/common/files.js
- generators/common/index.js
- generators/common/templates/.prettierignore.ejs
- generators/common/templates/.prettierrc.yml.ejs
- Fix cleanup and prettier error post code generation
- There is still an issue with prettier transform as the configs conflicts with one specified in base.
- Persist config options for overridden prompts
> Persist config options, fix prettier and clean generation

- generators/common/templates/README.md.ejs
> Add sapper specific instructions

- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/components/account/account-service.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/AccountMenu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/settings.svelte.ejs
Closes #16 
---
- Add user settings page to allow user to modify `first name`, `last name` and `email address` fields.
> Add account settings page

- .github/workflows/applications.yml
- .github/workflows/scripts/monolithic-session.json
- Dockerfile
- README.md
- generators/client/files.js
- generators/client/templates/svelte/cypress.json.ejs
- generators/client/templates/svelte/cypress/fixtures/example.json.ejs
- generators/client/templates/svelte/cypress/integration/spec.js.ejs
- generators/client/templates/svelte/cypress/plugins/index.js.ejs
- generators/client/templates/svelte/cypress/support/commands.js.ejs
- generators/client/templates/svelte/cypress/support/index.js.ejs
- generators/client/templates/svelte/package.json.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/register.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/init.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/settings.svelte.ejs
- generators/common/templates/.prettierignore.ejs
Closes #31 
---
- Integrate application generation, execute unit tests, integration tests, application packaging with production profile.
- Integrate Cypress tests run using development profile
> Add GitHub actions to verify the generated application

- generators/client/files.js
- generators/client/templates/svelte/cypress/integration/account/change-password.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/account/register.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/account/reset/init-password.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/footer.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/home.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/navbar.spec.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/Password.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/PasswordConfirm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/AccountMenu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/Footer.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/Navbar.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/password.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/register.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/init.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/settings.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/index.svelte.ejs
Closes #7 
- Tests to assert `user registration` page functionality
- Tests to assert `change password` page functionality
- Tests to assert `forgot password` page functionality
- Tests to assert `home` page functionality
- Tests to assert `navbar` functionality
- Tests to assert `footer` functionality
> Cypress e2e tests to verify flows

- generators/client/templates/svelte/package.json.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/AccountMenu.svelte.ejs
- package.json
> Fix account menu layout and default app version to 0.1

- generators/client/templates/svelte/cypress/support/commands.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/auth/auth-service.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/auth/auth-store.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/AccountMenu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/_layout.svelte.ejs
> Change api to check if user is authenticated

- generators/client/files.js
- generators/client/index.js
- generators/client/templates/svelte/package-template.json.ejs
- generators/client/templates/svelte/package.json
Closes #61 
---
An attempt to check if the generated application dependencies can be updated by dependabot
> Move dependencies outside to be updated by dependabot

- generators/client/templates/svelte/cypress/integration/account/register.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/account/reset/init-password.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/navbar.spec.js.ejs
- generators/client/templates/svelte/package.json
> Upgrade cypress dependency

- generators/client/templates/svelte/package.json
- generators/client/templates/svelte/rollup.config.js.ejs
> Upgrade rollup-plugin-svelte dependency

- generators/client/templates/svelte/package.json
> Update Svelte dependency

- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/components/Button.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/password.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/register.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/finish.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/init.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/settings.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/login.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/tailwind.css.ejs
Related #62 
--- 
Extract button component, and reuse in the different flows. Refactoring to move styles out of `tailwind.css` still needs to be done.
> Extract button component

- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/components/account/ChangePasswordForm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/ForgotPasswordForm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/RegisterUserForm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/ResetPasswordForm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/account/UserSettingsForm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/page/Form.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/page/Page.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/page/PageHeader.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/activate.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/password.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/register.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/finish.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/init.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/settings.svelte.ejs
Closes #62 
---
As part of this exercise, extracted `Page`, `PageHeader`, and `Form` generic components. Also, extracted page specific forms into their own component.
> Refactor pages using common layout

- .github/workflows/applications.yml
- .github/workflows/scripts/monolithic-jwt-gradle.json
- .github/workflows/scripts/monolithic-jwt-maven.json
- generators/client/templates/svelte/cypress/support/commands.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/auth/auth-service.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/auth/auth-store.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/AccountMenu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/login.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/utils/request.js.ejs
> feat: Support JWT authentication type

- generators/client/files.js
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-create.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-view.spec.js.ejs
- generators/client/templates/svelte/cypress/support/commands.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/SelectControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/admin/user-management/UserForm.svelte.ejs
> feat: E2e tests to verify create user flow

- generators/client/files.js
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-create.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-update.spec.js.ejs
> feat: E2e test to verify update user flow

- CHANGELOG.md
- generators/client/templates/svelte/src/main/webapp/app/routes/account/activate.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/password.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/register.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/finish.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/reset/init.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/account/settings.svelte.ejs
Closes #279 
Initial integration is used to forward alert messages. Further optimization can be done on a case-by-case basis.
> chore: Use svelte:fragment to wrap forwarded components

- .github/workflows/applications.yml
- Dockerfile
- generators/client/templates/svelte/src/main/webapp/app/components/admin/user-management/__tests__/user-table.spec.js.ejs
> Run frontend tests in CI and fix intermittent maven connectivity issue

- .github/workflows/applications-prod.yml
- generators/client/templates/svelte/cypress/integration/account/settings.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-list.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/login.spec.js.ejs
- generators/client/templates/svelte/cypress/support/commands.js.ejs
- GitHub CI pipeline to verify `mongodb` database type applications
- Improved cypress e2e tests stability
> feat: GitHub CI to verify mongodb prod pipeline

- .github/workflows/applications-prod.yml
- .github/workflows/applications.yml
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-create.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-list.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/home.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/navbar.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/routes.spec.js.ejs
- generators/client/templates/svelte/package.json
> Bump cypress and refresh CI cache

- generators/client/templates/svelte/.eslintrc.json.ejs
> Fix eslint config to scope execution of testing library rules to junit

- .github/workflows/applications-prod.yml
- .github/workflows/applications.yml
- generators/client/templates/svelte/package-template.json.ejs
- generators/common/templates/.prettierignore.ejs
- generators/common/templates/.prettierrc.ejs
> Fix prettier formatting of email templates

- .github/workflows/application-lighthouse.yml
- .github/workflows/scripts/data/lighthouserc.js
- .github/workflows/scripts/lighthouse/lighthouserc-auth.js
- .github/workflows/scripts/lighthouse/lighthouserc.js
- .github/workflows/scripts/lighthouse/puppeteer-auth.js
- .github/workflows/scripts/svelte-app-session-lighthouse.jdl
- generators/client/templates/svelte/src/main/webapp/app/components/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/SelectControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/components/layout/Navbar.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/login.svelte.ejs
- package-lock.json
> feat: Integrate Lighthouse CI

- generators/client/index.js
- generators/client/templates/svelte/package.json
- generators/client/templates/svelte/src/main/webapp/app/components/admin/user-management/UserListActions.spec.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/utils/validator.js.ejs
- package-lock.json
- package.json
> chore: Update prettier dependency

- cli/shipster.js
- package-lock.json
- package.json
> chore: Bump dependency

- generators/client/templates/svelte/src/main/webapp/app/app.html.ejs
Fix: https://sonarcloud.io/project/issues?id=jhipster_jhipster-sample-app-svelte&open=AXp9Q7O8pSoALX-ZL7BY&resolved=false&types=BUG
> Sonar: bug

- .github/workflows/application-lighthouse.yml
- .github/workflows/applications-prod.yml
- .github/workflows/applications.yml
- .github/workflows/generator.yml
- .github/workflows/release.yml
- Dockerfile
- Dockerfile-release
- package-lock.json
> feat: Support nodejs 16.x and npm 8.x

- .github/workflows/scripts/monolithic-jwt-maven-mongodb-prod.jdl
- .github/workflows/scripts/monolithic-oidc-maven-postgres-prod.jdl
- .github/workflows/scripts/monolithic-session-maven.jdl
- .github/workflows/scripts/svelte-app-session-lighthouse.jdl
- generators/client/templates/svelte/src/main/webapp/app/lib/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/utils/date.js.ejs
- generators/entity-client/files.js
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-create.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityForm.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityListActions.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/entity-service.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/[id]/edit.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/index.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/new.svelte.ejs
- package-lock.json
> feat: Support entity create and update flows for String, Instant and TextBlob field data types

- .github/workflows/scripts/monolithic-jwt-maven-mongodb-prod.jdl
- .github/workflows/scripts/monolithic-oidc-maven-postgres-prod.jdl
- .github/workflows/scripts/monolithic-session-maven.jdl
- .github/workflows/scripts/svelte-app-session-lighthouse.jdl
- generators/client/templates/svelte/src/main/webapp/app/lib/utils/validator.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-create.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityForm.svelte.ejs
> feat: Support numeric data field types in create and update flows

- .github/workflows/scripts/monolithic-jwt-maven-mongodb-prod.jdl
- .github/workflows/scripts/monolithic-oidc-maven-postgres-prod.jdl
- .github/workflows/scripts/monolithic-session-maven.jdl
- .github/workflows/scripts/svelte-app-session-lighthouse.jdl
- generators/client/templates/svelte/package.json
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityForm.svelte.ejs
> feat: Support create and update flows for boolean and date data types

- .github/workflows/application-lighthouse.yml
- .github/workflows/scripts/monolithic-jwt-maven-mongodb-prod.jdl
- .github/workflows/scripts/monolithic-oidc-maven-postgres-prod.jdl
- .github/workflows/scripts/monolithic-session-maven.jdl
- .github/workflows/scripts/svelte-app-session-lighthouse.jdl
- generators/client/templates/svelte/package.json
- generators/client/templates/svelte/src/main/webapp/app/lib/SelectControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/admin/user-management/UserForm.svelte.ejs
- generators/entity-client/files.js
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityForm.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/enums/enum.js.ejs
> feat: Support create and update flows for enum data type

- .github/workflows/scripts/monolithic-jwt-maven-mongodb-prod.jdl
- .github/workflows/scripts/monolithic-oidc-maven-postgres-prod.jdl
- .github/workflows/scripts/monolithic-session-maven.jdl
- .github/workflows/scripts/svelte-app-session-lighthouse.jdl
- generators/client/files.js
- generators/client/templates/svelte/cypress/support/commands.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/SelectControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/utils/data-util.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityForm.svelte.ejs
> feat: Support entity create and update flows for binary data types

- .github/workflows/application-lighthouse.yml
- generators/client/templates/svelte/src/main/webapp/app/lib/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/SelectControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/layout/EntityMenu.svelte.ejs
- generators/entity-client/files.js
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-create.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityForm.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/[id]/edit.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/new.svelte.ejs
> Polish create and update flows support

- .github/workflows/scripts/lighthouse/lighthouserc-auth.json
- generators/client/templates/svelte/src/main/webapp/app/lib/InputControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/SelectControl.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/admin/user-management/UserForm.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/page/Page.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/table/Table.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/admin/user-management/[id]/view.svelte.ejs
- generators/entity-client/files.js
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityForm.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/EntityTable.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/entity-service.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/user/user-service.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/[id]/edit.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/[id]/view.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/index.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/new.svelte.ejs
Closes #529
Closes #833 
Closes #834 
Closes #528
> feat: Support JDL relationships

- .github/dependabot.yml
- generators/app/index.js
- generators/app/prompts.js
- generators/client/files.js
- generators/client/index.js
- generators/client/templates/svelte/package.json
- generators/client/templates/svelte/src/main/webapp/app/lib/layout/admin-menu.svelte.ejs
- generators/client/templates/svelte/svelte.config.js.ejs
- generators/client/templates/svelte/swagger-package.json
- generators/common/files.js
- generators/common/index.js
- generators/common/templates/README.md.ejs
- generators/server/index.js
> feat: Support skipServer option

- generators/app/index.js
- generators/client/files.js
- generators/client/templates/svelte/src/main/webapp/app/lib/layout/admin-menu.svelte.ejs
- generators/client/templates/svelte/svelte.config.js.ejs
> feat: Support swagger-ui option

- generators/client/templates/svelte/src/main/webapp/swagger-ui/index.html.ejs
> Update swagger ui script to align with JHipster backend APIs

- .github/workflows/applications.yml
- .github/workflows/scripts/monolithic-oidc-maven-postgres-prod.jdl
- generators/client/templates/svelte/cypress.json.ejs
- generators/client/templates/svelte/package.json
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
> chore: Bump cypress dependency and fix e2e issue

- README.md
> chore: Update readme application example to resolve generation issues

- generators/client/templates/svelte/cypress.json.ejs
- generators/client/templates/svelte/cypress/integration/account/change-password.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/account/settings.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/logger.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-create.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-delete.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-list.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-update.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-view.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/home.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/navbar.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/routes.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-create.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-delete.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-list.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-view.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/support/entities/entity-util.js.ejs
> chore: Rename cypress environment variables

- .github/workflows/applications.yml
- .github/workflows/scripts/monolithic-session-maven-reactive.jdl
- generators/app/index.js
- generators/app/prompts.js
- generators/client/templates/svelte/cypress/integration/admin/logger.spec.js.ejs
- generators/client/templates/svelte/cypress/integration/admin/user-management/user-list.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-delete.spec.js.ejs
- generators/server/files.js
- generators/server/index.js
- generators/server/templates/src/main/java/package/config/SecurityConfiguration_reactive.java.ejs
- generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs
Related #530 
Closes #519 
---
Override Reactive stack Security and User resource Java code to fix issues identified during integration. I will raise PR against the main and once that code is available in the next release, we can remove the override.
> Support reactive monolithic and gateway applications

- .github/workflows/applications.yml
- .github/workflows/scripts/microservices-oidc-maven-prod.jdl
- generators/app/index.js
- generators/client/index.js
- generators/client/templates/svelte/package.json
- generators/common/templates/.gitignore.ejs
- generators/common/templates/.prettierrc.ejs
- generators/common/templates/sonar-project.properties.ejs
- generators/entity-client/files.js
- generators/entity-client/index.js
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-delete.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-list.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-update.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/integration/entities/entity/entity-view.spec.js.ejs
- generators/entity-client/templates/svelte/cypress/support/entities/entity-util.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/[id]/edit.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/new.svelte.ejs
- generators/server/files.js
- generators/server/index.js
- generators/server/templates/package.json
- generators/server/templates/package.json.ejs
Closes #530 
---
- Synchronize JHipster templates overridden in the blueprint
- Correct relationships import path in svelte and cypress code
- CI job to verify micro-services application generation
> feat: Support micro-services application generation

- .github/workflows/applications.yml
- .github/workflows/scripts/microservices-oidc-maven-prod.jdl
- generators/client/templates/svelte/src/main/webapp/swagger-ui/index.html.ejs
> feat: Support swagger api docs in micro-service apps

- generators/client/templates/svelte/cypress/integration/routes.spec.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/auth/auth-guard.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/auth/auth-store.js.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/login.svelte.ejs
> feat: On successful login, redirect to saved navigation context

- generators/entity-client/files.js
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/entity-list-actions.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/entity-table.spec.js.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/entity-table.svelte.ejs
> feat: Generate unit tests for entity table component

- generators/client/index.js
- generators/common/templates/.prettierrc.ejs
- generators/entity-client/index.js
- package-lock.json
- package.json
Correct formatting also requires a change on JHipster side and hopefully should be available in next release
> chore: Remove files during upgrade, reformat correctly during upgrade

- generators/client/templates/svelte/package.json
- generators/client/templates/svelte/src/main/webapp/app/lib/account/account-menu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/admin/admin-menu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/admin/user-management/user-form.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/admin/user-management/user-list-actions.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/entities/entity-menu.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/layout/footer.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/layout/navbar.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/admin/user-management/[id]/view.svelte.ejs
- generators/client/templates/svelte/src/main/webapp/app/routes/admin/user-management/index.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/lib/entities/entity/entity-form.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/[id]/view.svelte.ejs
- generators/entity-client/templates/svelte/src/main/webapp/app/routes/entities/entity/index.svelte.ejs
Fixes issue of intermittent display of icons
> fix: Use esm imports for font awesome icons

- generators/client/templates/svelte/src/main/webapp/app/global.css.ejs
- generators/client/templates/svelte/src/main/webapp/app/lib/auth/auth-store.js.ejs
> fix: Sonar violations identified in the last release

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> fix: Include prettier, plugins as runtime dependencies

- generators/client/templates/svelte/src/main/webapp/app/app.html.ejs
- generators/client/templates/svelte/vite.config.js.ejs
> fix: Redirect to Oauth2 API in dev mode

- generators/client/templates/svelte/.eslintrc.json.ejs
- generators/client/templates/svelte/package.json
> Replace eslint-plugin-svelte3 with eslint-plugin-svelte

- .github/workflows/applications.yml
> fix: Disable cypress tests in ms oidc flow

- generators/client/templates/package.json
- generators/client/templates/vitest/package.json
> chore: Update vite, vitest dependencies

- generators/client/files.js
- generators/client/templates/package.json
- generators/client/templates/src/main/webapp/app/lib/admin/user-management/user-form.spec.js.ejs
> feat: add unit tests for user form component
